### ISSUE TITLE
Remove empty keywords prior to upload

### ISSUE THREAD

**Issue by seanhardison1** [andybeet/InportXML#4]

**Comment by andybeet** [comment]
What are the effects of not doing this?

for example,
Does this cause an issue when uploading?
Does it create metadata fields in InPort with missing values?

**Comment by seanhardison1** [comment]
Having empty keywords in the xml results in a warning message but doesn't prevent upload. This is low priority, but may be worth considering for aesthetics in the future :male_detective:
