### ISSUE TITLE
remove openMasterTemplate.R?

### ISSUE THREAD

**Issue by andybeet** [andybeet/InportXML#8]
@seanhardison1 Should we remove this function? I have created another function that copies the master_template file to the users working directory. I think this new function may be platform independent unlike openMasterTemplate. Want to test it on your mac?

**Comment by seanhardison1** [comment]
Yes, I think that's a good idea. I'll test out the new one!

**Comment by seanhardison1** [comment]
It works!

**Comment by andybeet** [comment]
ok. i'll delete the file in question and close this
